In [1]:
import pandas as pd
import numpy as np

In [2]:
df_sensus = pd.read_csv("data_sensus_penduduk_1971-2010.csv")
df_sensus["Provinsi"] = df_sensus["Provinsi"].replace("INDONESIA", "Indonesia")
df_sensus

,Provinsi,1971,1980,1990,1995,2000,2010
0,Aceh,2008595.0,2611271.0,3416156.0,3847583.0,3930905.0,4494410
1,Sumatera Utara,6621831.0,8360894.0,10256027.0,11114667.0,11649655.0,12982204
2,Sumatera Barat,2793196.0,3406816.0,4000207.0,4323170.0,4248931.0,4846909
3,Riau,1641545.0,2168535.0,3303976.0,3900534.0,4957627.0,5538367
4,Jambi,1006084.0,1445994.0,2020568.0,2369959.0,2413846.0,3092265
5,Sumatera Selatan,3440573.0,4629801.0,6313074.0,7207545.0,6899675.0,7450394
6,Bengkulu,519316.0,768064.0,1179122.0,1409117.0,1567432.0,1715518
7,Lampung,2777008.0,4624785.0,6017573.0,6657759.0,6741439.0,7608405
8,Kepulauan Bangka Belitung,NaN,NaN,NaN,NaN,900197.0,1223296
9,Kepulauan Riau,NaN,NaN,NaN,NaN,NaN,1679163
10,DKI Jakarta,4579303.0,6503449.0,8259266.0,9112652.0,8389443.0,9607787
11,Jawa Barat,21623529.0,27453525.0,35384352.0,39206787.0,35729537.0,43053732
12,Jawa Tengah,21877136.0,25372889.0,28520643.0,29653266.0,31228940.0,32382657
13,DI Yogyakarta,2489360.0,2750813.0,2913054.0,2916779.0,3122268.0,3457491
14,Jawa Timur,25516999.0,29188852.0,32503991.0,33844002.0,34783640.0,37476757
15,Banten,NaN,NaN,NaN,NaN,8098780.0,10632166
16,Bali,2120322.0,2469930.0,2777811.0,2895649.0,3151162.0,3890757
17,Nusa Tenggara Barat,2203465.0,2724664.0,3369649.0,3645713.0,4009261.0,4500212
18,Nusa Tenggara Timur,2295287.0,2737166.0,3268644.0,3577472.0,3952279.0,4683827
19,Kalimantan Barat,2019936.0,2486068.0,3229153.0,3635730.0,4034198.0,4395983
20,Kalimantan Tengah,701936.0,954353.0,1396486.0,1627453.0,1857000.0,2212089
21,Kalimantan Selatan,1699105.0,2064649.0,2597572.0,2893477.0,2985240.0,3626616
22,Kalimantan Timur,733797.0,1218016.0,1876663.0,2314183.0,2455120.0,3553143
23,Sulawesi Utara,1718543.0,2115384.0,2478119.0,2649093.0,2012098.0,2270596
24,Sulawesi Tengah,913662.0,1289635.0,1711327.0,1938071.0,2218435.0,2635009
25,Sulawesi Selatan,5180576.0,6062212.0,6981646.0,7558368.0,8059627.0,8034776
26,Sulawesi Tenggara,714120.0,942302.0,1349619.0,1586917.0,1821284.0,2232586
27,Gorontalo,NaN,NaN,NaN,NaN,835044.0,1040164
28,Sulawesi Barat,NaN,NaN,NaN,NaN,NaN,1158651
29,Maluku,1089565.0,1411006.0,1857790.0,2086516.0,1205539.0,1533506
30,Maluku Utara,NaN,NaN,NaN,NaN,785059.0,1038087
31,Papua Barat,NaN,NaN,NaN,NaN,NaN,760422
32,Papua,923440.0,1173875.0,1648708.0,1942627.0,2220934.0,2833381
33,Indonesia,119208229.0,147490298.0,179378946.0,194754808.0,206264595.0,237641326

In [3]:
df_2010 = pd.read_csv("data_penduduk_2010.csv")

df_2010["Jumlah Penduduk (Ribu)"] = df_2010["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
df_2010["Laju Pertumbuhan Penduduk per Tahun"] = df_2010["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
df_2010["Persentase Penduduk"] = df_2010["Persentase Penduduk"].str.replace(',', '.')
df_2010["Kepadatan Penduduk per km persegi (km2)"] = df_2010["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
df_2010["Rasio Jenis Kelamin Penduduk"] = df_2010["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

df_2010["Jumlah Penduduk (Ribu)"] = df_2010["Jumlah Penduduk (Ribu)"].str.replace(' ', '')
df_2010["Laju Pertumbuhan Penduduk per Tahun"] = df_2010["Laju Pertumbuhan Penduduk per Tahun"].str.replace(' ', '')
df_2010["Persentase Penduduk"] = df_2010["Persentase Penduduk"].str.replace(' ', '')
df_2010["Kepadatan Penduduk per km persegi (km2)"] = df_2010["Kepadatan Penduduk per km persegi (km2)"].str.replace(' ', '')
df_2010["Rasio Jenis Kelamin Penduduk"] = df_2010["Rasio Jenis Kelamin Penduduk"].str.replace(' ', '')

df_2010

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (km2),Rasio Jenis Kelamin Penduduk
0,Aceh,4523.1,2.36,1.90,78,99.4
1,Sumatera Utara,13028.7,1.10,5.46,179,99.4
2,Sumatera Barat,4865.3,1.34,2.04,116,98.1
3,Riau,5574.9,3.58,2.34,64,105.9
4,Jambi,3107.6,2.56,1.30,62,104.2
5,Sumatera Selatan,7481.6,1.85,3.14,82,103.3
6,Bengkulu,1722.1,1.67,0.72,86,104.2
7,Lampung,7634.0,1.24,3.20,220,105.7
8,Kepulauan Bangka Belitung,1230.2,3.14,0.52,75,107.6
9,Kepulauan Riau,1692.8,4.95,0.71,206,105.2
10,DKI Jakarta,9640.4,1.41,4.04,14518,102.5
11,Jawa Barat,43227.1,1.90,18.12,1222,103.2
12,Jawa Tengah,32443.9,0.37,13.60,989,98.4
13,DI Yogyakarta,3467.5,1.04,1.45,1107,97.4
14,Jawa Timur,37565.7,0.76,15.75,786,97.2
15,Banten,10688.6,2.78,4.48,1106,104.4
16,Bali,3907.4,2.15,1.64,676,101.3
17,Nusa Tenggara Barat,4516.1,1.17,1.89,243,93.9
18,Nusa Tenggara Timur,4706.2,2.07,1.97,97,98.3
19,Kalimantan Barat,4411.4,0.91,1.85,30,104.3
20,Kalimantan Tengah,2220.8,1.79,0.93,14,108.6
21,Kalimantan Selatan,3642.6,1.99,1.53,94,102.2
22,Kalimantan Timur,3047.5,3.81,1.50,17,110.9
23,Kalimantan Utara,528.6,NaN,NaN,NaN,NaN
24,Sulawesi Utara,2277.7,1.28,0.95,164,104.1
25,Sulawesi Tengah,2646.0,1.95,1.11,43,104.8
26,Sulawesi Selatan,8060.4,1.17,3.38,173,95.1
27,Sulawesi Tenggara,2243.6,2.08,0.94,59,100.6
28,Gorontalo,1044.8,2.26,0.44,93,100.3
29,Sulawesi Barat,1164.6,2.68,0.49,69,100.4
30,Maluku,1541.9,2.80,0.65,33,101.9
31,Maluku Utara,1043.3,2.47,0.44,33,104.5
32,Papua Barat,765.3,3.71,0.32,8,112.0
33,Papua,2857.0,5.39,1.20,9,113.0
34,Indonesia,238518.8,1.49,100.00,124,101.0

In [4]:
# df_2015 = pd.read_csv("data_proyeksi_penduduk_2015.csv")

# df_2015["Jumlah Penduduk (Ribu)"] = df_2015["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
# df_2015["Laju Pertumbuhan Penduduk per Tahun"] = df_2015["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
# df_2015["Persentase Penduduk"] = df_2015["Persentase Penduduk"].str.replace(',', '.')
# df_2015["Kepadatan Penduduk per km persegi (km2)"] = df_2015["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
# df_2015["Rasio Jenis Kelamin Penduduk"] = df_2015["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

# df_2015

In [5]:
df_2016 = pd.read_csv("data_proyeksi_penduduk_2016.csv")

df_2016["Jumlah Penduduk (Ribu)"] = df_2016["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
df_2016["Laju Pertumbuhan Penduduk per Tahun"] = df_2016["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
df_2016["Persentase Penduduk"] = df_2016["Persentase Penduduk"].str.replace(',', '.')
df_2016["Kepadatan Penduduk per km persegi (km2)"] = df_2016["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
df_2016["Rasio Jenis Kelamin Penduduk"] = df_2016["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

df_2016["Jumlah Penduduk (Ribu)"] = df_2016["Jumlah Penduduk (Ribu)"].str.replace(' ', '')
df_2016["Laju Pertumbuhan Penduduk per Tahun"] = df_2016["Laju Pertumbuhan Penduduk per Tahun"].str.replace(' ', '')
df_2016["Persentase Penduduk"] = df_2016["Persentase Penduduk"].str.replace(' ', '')
df_2016["Kepadatan Penduduk per km persegi (km2)"] = df_2016["Kepadatan Penduduk per km persegi (km2)"].str.replace(' ', '')
df_2016["Rasio Jenis Kelamin Penduduk"] = df_2016["Rasio Jenis Kelamin Penduduk"].str.replace(' ', '')

df_2016

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (km2),Rasio Jenis Kelamin Penduduk
0,Aceh,5096.2,2.01,1.97,88,99.8
1,Sumatera Utara,14102.9,1.33,5.45,193,99.6
2,Sumatera Barat,5259.5,1.31,2.03,125,99.1
3,Riau,6501.0,2.59,2.51,75,105.5
4,Jambi,3458.9,1.80,1.34,69,104.2
5,Sumatera Selatan,8160.9,1.46,3.15,89,103.3
6,Bengkulu,1904.8,1.69,0.74,96,104.0
7,Lampung,8205.1,1.21,3.17,237,105.2
8,Kepulauan Bangka Belitung,1401.8,2.20,0.54,85,108.2
9,Kepulauan Riau,2028.2,3.06,0.78,247,104.3
10,DKI Jakarta,10277.6,1.07,3.97,15478,100.8
11,Jawa Barat,47379.4,1.54,18.31,1339,102.8
12,Jawa Tengah,34019.1,0.79,13.15,1037,98.4
13,DI Yogyakarta,3720.9,1.18,1.44,1188,97.8
14,Jawa Timur,39075.3,0.66,15.10,817,97.5
15,Banten,12203.1,2.23,4.72,1263,104.0
16,Bali,4200.1,1.21,1.62,727,101.4
17,Nusa Tenggara Barat,4896.2,1.36,1.89,264,94.3
18,Nusa Tenggara Timur,5203.5,1.69,2.01,107,98.2
19,Kalimantan Barat,4861.7,1.63,1.88,33,103.8
20,Kalimantan Tengah,2550.2,2.33,0.99,17,109.4
21,Kalimantan Selatan,4055.5,1.81,1.57,105,102.8
22,Kalimantan Timur,3501.2,2.58,1.35,27,110.3
23,Kalimantan Utara,666.3,...,0.26,9,113.0
24,Sulawesi Utara,2436.9,1.13,0.94,176,104.2
25,Sulawesi Tengah,2921.7,1.67,1.13,47,104.4
26,Sulawesi Selatan,8606.4,1.10,3.33,184,95.5
27,Sulawesi Tenggara,2551.0,2.16,0.99,67,101.1
28,Gorontalo,1150.8,1.62,0.44,102,100.4
29,Sulawesi Barat,1306.5,1.93,0.51,78,100.7
30,Maluku,1715.5,1.79,0.66,37,101.7
31,Maluku Utara,1185.9,2.16,0.46,37,104.2
32,Papua Barat,893.4,2.61,0.35,9,111.3
33,Papua,3207.4,1.95,1.24,10,111.4
34,Indonesia,258705.0,1.36,100.00,135,101.0

In [6]:
df_2017 = pd.read_csv("data_proyeksi_penduduk_2017.csv")

df_2017["Jumlah Penduduk (Ribu)"] = df_2017["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
df_2017["Laju Pertumbuhan Penduduk per Tahun"] = df_2017["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
df_2017["Persentase Penduduk"] = df_2017["Persentase Penduduk"].str.replace(',', '.')
df_2017["Kepadatan Penduduk per km persegi (km2)"] = df_2017["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
df_2017["Rasio Jenis Kelamin Penduduk"] = df_2017["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

df_2017["Jumlah Penduduk (Ribu)"] = df_2017["Jumlah Penduduk (Ribu)"].str.replace(' ', '')
df_2017["Laju Pertumbuhan Penduduk per Tahun"] = df_2017["Laju Pertumbuhan Penduduk per Tahun"].str.replace(' ', '')
df_2017["Persentase Penduduk"] = df_2017["Persentase Penduduk"].str.replace(' ', '')
df_2017["Kepadatan Penduduk per km persegi (km2)"] = df_2017["Kepadatan Penduduk per km persegi (km2)"].str.replace(' ', '')
df_2017["Rasio Jenis Kelamin Penduduk"] = df_2017["Rasio Jenis Kelamin Penduduk"].str.replace(' ', '')

df_2017

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (km2),Rasio Jenis Kelamin Penduduk
0,Aceh,5189.5,1.98,1.98,90,99.8
1,Sumatera Utara,14262.1,1.30,5.45,195,99.6
2,Sumatera Barat,5321.5,1.29,2.03,127,99.2
3,Riau,6657.9,2.57,2.54,77,105.4
4,Jambi,3515.0,1.78,1.34,70,104.2
5,Sumatera Selatan,8267.0,1.44,3.16,90,103.3
6,Bengkulu,1934.3,1.67,0.74,97,104.0
7,Lampung,8289.6,1.18,3.17,239,105.1
8,Kepulauan Bangka Belitung,1430.9,2.18,0.55,87,108.3
9,Kepulauan Riau,2082.7,3.01,0.80,254,104.2
10,DKI Jakarta,10374.2,1.05,3.96,15624,100.6
11,Jawa Barat,48037.6,1.52,18.34,1358,102.7
12,Jawa Tengah,34257.9,0.78,13.08,1044,98.4
13,DI Yogyakarta,3762.2,1.17,1.44,1201,97.9
14,Jawa Timur,39293.0,0.64,15.00,822,97.5
15,Banten,12448.2,2.20,4.75,1288,103.9
16,Bali,4246.5,1.20,1.62,735,101.4
17,Nusa Tenggara Barat,4955.6,1.34,1.89,267,94.3
18,Nusa Tenggara Timur,5287.3,1.68,2.02,109,98.2
19,Kalimantan Barat,4932.5,1.61,1.88,33,103.7
20,Kalimantan Tengah,2605.3,2.31,0.99,17,109.5
21,Kalimantan Selatan,4119.8,1.77,1.57,106,102.9
22,Kalimantan Timur,3575.4,2.31,1.37,28,110.2
23,Kalimantan Utara,691.1,3.90,0.26,9,113.0
24,Sulawesi Utara,2461.0,1.11,0.94,178,104.2
25,Sulawesi Tengah,2966.3,1.65,1.13,48,104.3
26,Sulawesi Selatan,8690.3,1.08,3.32,186,95.5
27,Sulawesi Tenggara,2602.4,2.14,0.99,68,101.1
28,Gorontalo,1168.2,1.61,0.45,104,100.4
29,Sulawesi Barat,1331.0,1.93,0.51,79,100.7
30,Maluku,1744.7,1.78,0.67,37,101.7
31,Maluku Utara,1209.3,2.13,0.46,38,104.1
32,Papua Barat,915.4,2.59,0.35,9,111.2
33,Papua,3265.2,1.93,1.25,10,111.1
34,Indonesia,261890.9,1.34,100.00,137,101.0

In [7]:
df_2018 = pd.read_csv("data_proyeksi_penduduk_2018.csv")

df_2018["Jumlah Penduduk (Ribu)"] = df_2018["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
df_2018["Laju Pertumbuhan Penduduk per Tahun"] = df_2018["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
df_2018["Persentase Penduduk"] = df_2018["Persentase Penduduk"].str.replace(',', '.')
df_2018["Kepadatan Penduduk per km persegi (km2)"] = df_2018["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
df_2018["Rasio Jenis Kelamin Penduduk"] = df_2018["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

df_2018["Jumlah Penduduk (Ribu)"] = df_2018["Jumlah Penduduk (Ribu)"].str.replace(' ', '')
df_2018["Laju Pertumbuhan Penduduk per Tahun"] = df_2018["Laju Pertumbuhan Penduduk per Tahun"].str.replace(' ', '')
df_2018["Persentase Penduduk"] = df_2018["Persentase Penduduk"].str.replace(' ', '')
df_2018["Kepadatan Penduduk per km persegi (km2)"] = df_2018["Kepadatan Penduduk per km persegi (km2)"].str.replace(' ', '')
df_2018["Rasio Jenis Kelamin Penduduk"] = df_2018["Rasio Jenis Kelamin Penduduk"].str.replace(' ', '')

df_2018

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (km2),Rasio Jenis Kelamin Penduduk
0,Aceh,5281.3,1.96,1.99,91,99.8
1,Sumatera Utara,14415.4,1.27,5.44,198,99.6
2,Sumatera Barat,5382.1,1.27,2.03,128,99.3
3,Riau,6814.9,2.54,2.57,78,105.3
4,Jambi,3570.3,1.75,1.35,71,104.1
5,Sumatera Selatan,8370.3,1.41,3.16,91,103.3
6,Bengkulu,1963.3,1.65,0.74,99,103.9
7,Lampung,8370.5,1.16,3.16,242,105.0
8,Kepulauan Bangka Belitung,1459.9,2.16,0.55,89,108.4
9,Kepulauan Riau,2136.5,2.95,0.81,260,104.0
10,DKI Jakarta,10467.6,1.03,3.95,15764,100.4
11,Jawa Barat,48683.7,1.50,18.37,1376,102.6
12,Jawa Tengah,34490.8,0.77,13.01,1052,98.3
13,DI Yogyakarta,3802.9,1.16,1.43,1214,97.9
14,Jawa Timur,39500.9,0.63,14.91,826,97.5
15,Banten,12689.7,2.17,4.79,1313,103.9
16,Bali,4292.2,1.18,1.62,743,101.4
17,Nusa Tenggara Barat,5013.7,1.32,1.89,270,94.3
18,Nusa Tenggara Timur,5371.5,1.67,2.03,110,98.1
19,Kalimantan Barat,5001.7,1.58,1.89,34,103.6
20,Kalimantan Tengah,2660.2,2.28,1.00,17,109.6
21,Kalimantan Selatan,4182.7,1.74,1.58,108,103.0
22,Kalimantan Timur,3648.8,2.28,1.38,28,110.2
23,Kalimantan Utara,716.4,3.87,0.27,9,113.0
24,Sulawesi Utara,2484.4,1.09,0.94,179,104.2
25,Sulawesi Tengah,3010.4,1.63,1.14,49,104.2
26,Sulawesi Selatan,8772.0,1.06,3.31,188,95.6
27,Sulawesi Tenggara,2653.7,2.12,1.00,70,101.2
28,Gorontalo,1185.5,1.59,0.45,105,100.4
29,Sulawesi Barat,1355.6,1.92,0.51,81,100.8
30,Maluku,1773.8,1.77,0.67,38,101.7
31,Maluku Utara,1232.6,2.11,0.47,39,104.1
32,Papua Barat,937.5,2.57,0.35,9,111.1
33,Papua,3322.5,1.90,1.25,10,110.9
34,Indonesia,265015.3,1.33,100.00,138,101.0

In [8]:
df_2019 = pd.read_csv("data_proyeksi_penduduk_2019.csv")

df_2019["Jumlah Penduduk (Ribu)"] = df_2019["Jumlah Penduduk (Ribu)"].str.replace(',', '.')
df_2019["Laju Pertumbuhan Penduduk per Tahun"] = df_2019["Laju Pertumbuhan Penduduk per Tahun"].str.replace(',', '.')
df_2019["Persentase Penduduk"] = df_2019["Persentase Penduduk"].str.replace(',', '.')
df_2019["Kepadatan Penduduk per km persegi (km2)"] = df_2019["Kepadatan Penduduk per km persegi (km2)"].str.replace(',', '.')
df_2019["Rasio Jenis Kelamin Penduduk"] = df_2019["Rasio Jenis Kelamin Penduduk"].str.replace(',', '.')

df_2019["Jumlah Penduduk (Ribu)"] = df_2019["Jumlah Penduduk (Ribu)"].str.replace(' ', '')
df_2019["Laju Pertumbuhan Penduduk per Tahun"] = df_2019["Laju Pertumbuhan Penduduk per Tahun"].str.replace(' ', '')
df_2019["Persentase Penduduk"] = df_2019["Persentase Penduduk"].str.replace(' ', '')
df_2019["Kepadatan Penduduk per km persegi (km2)"] = df_2019["Kepadatan Penduduk per km persegi (km2)"].replace(' ', '')
df_2019["Rasio Jenis Kelamin Penduduk"] = df_2019["Rasio Jenis Kelamin Penduduk"].str.replace(' ', '')

df_2019

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (km2),Rasio Jenis Kelamin Penduduk
0,Aceh,5371.5,1.93,2.00,93,99.9
1,Sumatera Utara,14562.5,1.24,5.43,200,99.6
2,Sumatera Barat,5441.2,1.25,2.03,130,99.4
3,Riau,6971.7,2.52,2.60,80,105.2
4,Jambi,3624.6,1.72,1.35,72,104.1
5,Sumatera Selatan,8470.7,1.39,3.16,92,103.3
6,Bengkulu,1991.8,1.63,0.74,100,103.9
7,Lampung,8447.7,1.13,3.15,244,104.9
8,Kepulauan Bangka Belitung,1488.8,2.14,0.56,91,108.4
9,Kepulauan Riau,2189.7,2.90,0.82,267,103.9
10,DKI Jakarta,10557.8,1.02,3.94,15 900,100.2
11,Jawa Barat,49316.7,1.48,18.40,1 394,102.5
12,Jawa Tengah,34718.2,0.76,12.95,1 058,98.3
13,DI Yogyakarta,3842.9,1.15,1.43,1 227,98.0
14,Jawa Timur,39698.6,0.62,14.81,831,97.5
15,Banten,12927.3,2.14,4.82,1 338,103.8
16,Bali,4336.9,1.17,1.62,750,101.5
17,Nusa Tenggara Barat,5070.4,1.29,1.89,273,94.4
18,Nusa Tenggara Timur,5456.2,1.66,2.04,112,98.1
19,Kalimantan Barat,5069.1,1.56,1.89,34,103.5
20,Kalimantan Tengah,2714.9,2.26,1.01,18,109.7
21,Kalimantan Selatan,4244.1,1.71,1.58,110,103.0
22,Kalimantan Timur,3721.4,2.24,1.39,29,110.2
23,Kalimantan Utara,742.2,3.84,0.28,10,112.8
24,Sulawesi Utara,2507.0,1.07,0.94,181,104.1
25,Sulawesi Tengah,3054.0,1.61,1.14,49,104.2
26,Sulawesi Selatan,8851.2,1.05,3.30,189,95.6
27,Sulawesi Tenggara,2704.7,2.10,1.01,71,101.2
28,Gorontalo,1202.6,1.58,0.45,107,100.4
29,Sulawesi Barat,1380.3,1.91,0.51,82,100.8
30,Maluku,1802.9,1.75,0.67,38,101.6
31,Maluku Utara,1255.8,2.08,0.47,39,104.0
32,Papua Barat,959.6,2.55,0.36,9,111.0
33,Papua,3379.3,1.88,1.26,11,110.6
34,Indonesia,268074.6,1.31,100.00,140,100.9

In [9]:
df_merged = pd.merge(df_sensus, df_2016[['Provinsi','Jumlah Penduduk (Ribu)']], how = 'right', 
                     left_on = 'Provinsi', right_on = 'Provinsi')
df_merged.rename(columns={'Jumlah Penduduk (Ribu)': '2016'}, inplace=True)

df_merged = pd.merge(df_merged, df_2017[['Provinsi','Jumlah Penduduk (Ribu)']], how = 'left', 
                     left_on = 'Provinsi', right_on = 'Provinsi')
df_merged.rename(columns={'Jumlah Penduduk (Ribu)': '2017'}, inplace=True)

df_merged = pd.merge(df_merged, df_2018[['Provinsi','Jumlah Penduduk (Ribu)']], how = 'left', 
                     left_on = 'Provinsi', right_on = 'Provinsi')
df_merged.rename(columns={'Jumlah Penduduk (Ribu)': '2018'}, inplace=True)

df_merged = pd.merge(df_merged, df_2019[['Provinsi','Jumlah Penduduk (Ribu)']], how = 'left', 
                     left_on = 'Provinsi', right_on = 'Provinsi')
df_merged.rename(columns={'Jumlah Penduduk (Ribu)': '2019'}, inplace=True)

df_merged.iloc[:, 7:] = df_merged.iloc[:, 7:].astype(float)
# Dikali 1000 sehingga tidak dalam ribu lagi
df_merged.iloc[:, 7:] = np.round((df_merged.iloc[:, 7:] * 1000), 1)

df_merged.to_csv("../jumlah_penduduk_1971-2019.csv", encoding='utf-8', index=False)

df_merged

,Provinsi,1971,1980,1990,1995,2000,2010,2016,2017,2018,2019
0,Aceh,2008595.0,2611271.0,3416156.0,3847583.0,3930905.0,4494410.0,5096200.0,5189500.0,5281300.0,5371500.0
1,Sumatera Utara,6621831.0,8360894.0,10256027.0,11114667.0,11649655.0,12982204.0,14102900.0,14262100.0,14415400.0,14562500.0
2,Sumatera Barat,2793196.0,3406816.0,4000207.0,4323170.0,4248931.0,4846909.0,5259500.0,5321500.0,5382100.0,5441200.0
3,Riau,1641545.0,2168535.0,3303976.0,3900534.0,4957627.0,5538367.0,6501000.0,6657900.0,6814900.0,6971700.0
4,Jambi,1006084.0,1445994.0,2020568.0,2369959.0,2413846.0,3092265.0,3458900.0,3515000.0,3570300.0,3624600.0
5,Sumatera Selatan,3440573.0,4629801.0,6313074.0,7207545.0,6899675.0,7450394.0,8160900.0,8267000.0,8370300.0,8470700.0
6,Bengkulu,519316.0,768064.0,1179122.0,1409117.0,1567432.0,1715518.0,1904800.0,1934300.0,1963300.0,1991800.0
7,Lampung,2777008.0,4624785.0,6017573.0,6657759.0,6741439.0,7608405.0,8205100.0,8289600.0,8370500.0,8447700.0
8,Kepulauan Bangka Belitung,NaN,NaN,NaN,NaN,900197.0,1223296.0,1401800.0,1430900.0,1459900.0,1488800.0
9,Kepulauan Riau,NaN,NaN,NaN,NaN,NaN,1679163.0,2028200.0,2082700.0,2136500.0,2189700.0
10,DKI Jakarta,4579303.0,6503449.0,8259266.0,9112652.0,8389443.0,9607787.0,10277600.0,10374200.0,10467600.0,10557800.0
11,Jawa Barat,21623529.0,27453525.0,35384352.0,39206787.0,35729537.0,43053732.0,47379400.0,48037600.0,48683700.0,49316700.0
12,Jawa Tengah,21877136.0,25372889.0,28520643.0,29653266.0,31228940.0,32382657.0,34019100.0,34257900.0,34490800.0,34718200.0
13,DI Yogyakarta,2489360.0,2750813.0,2913054.0,2916779.0,3122268.0,3457491.0,3720900.0,3762200.0,3802900.0,3842900.0
14,Jawa Timur,25516999.0,29188852.0,32503991.0,33844002.0,34783640.0,37476757.0,39075300.0,39293000.0,39500900.0,39698600.0
15,Banten,NaN,NaN,NaN,NaN,8098780.0,10632166.0,12203100.0,12448200.0,12689700.0,12927300.0
16,Bali,2120322.0,2469930.0,2777811.0,2895649.0,3151162.0,3890757.0,4200100.0,4246500.0,4292200.0,4336900.0
17,Nusa Tenggara Barat,2203465.0,2724664.0,3369649.0,3645713.0,4009261.0,4500212.0,4896200.0,4955600.0,5013700.0,5070400.0
18,Nusa Tenggara Timur,2295287.0,2737166.0,3268644.0,3577472.0,3952279.0,4683827.0,5203500.0,5287300.0,5371500.0,5456200.0
19,Kalimantan Barat,2019936.0,2486068.0,3229153.0,3635730.0,4034198.0,4395983.0,4861700.0,4932500.0,5001700.0,5069100.0
20,Kalimantan Tengah,701936.0,954353.0,1396486.0,1627453.0,1857000.0,2212089.0,2550200.0,2605300.0,2660200.0,2714900.0
21,Kalimantan Selatan,1699105.0,2064649.0,2597572.0,2893477.0,2985240.0,3626616.0,4055500.0,4119800.0,4182700.0,4244100.0
22,Kalimantan Timur,733797.0,1218016.0,1876663.0,2314183.0,2455120.0,3553143.0,3501200.0,3575400.0,3648800.0,3721400.0
23,Kalimantan Utara,NaN,NaN,NaN,NaN,NaN,NaN,666300.0,691100.0,716400.0,742200.0
24,Sulawesi Utara,1718543.0,2115384.0,2478119.0,2649093.0,2012098.0,2270596.0,2436900.0,2461000.0,2484400.0,2507000.0
25,Sulawesi Tengah,913662.0,1289635.0,1711327.0,1938071.0,2218435.0,2635009.0,2921700.0,2966300.0,3010400.0,3054000.0
26,Sulawesi Selatan,5180576.0,6062212.0,6981646.0,7558368.0,8059627.0,8034776.0,8606400.0,8690300.0,8772000.0,8851200.0
27,Sulawesi Tenggara,714120.0,942302.0,1349619.0,1586917.0,1821284.0,2232586.0,2551000.0,2602400.0,2653700.0,2704700.0
28,Gorontalo,NaN,NaN,NaN,NaN,835044.0,1040164.0,1150800.0,1168200.0,1185500.0,1202600.0
29,Sulawesi Barat,NaN,NaN,NaN,NaN,NaN,1158651.0,1306500.0,1331000.0,1355600.0,1380300.0
30,Maluku,1089565.0,1411006.0,1857790.0,2086516.0,1205539.0,1533506.0,1715500.0,1744700.0,1773800.0,1802900.0
31,Maluku Utara,NaN,NaN,NaN,NaN,785059.0,1038087.0,1185900.0,1209300.0,1232600.0,1255800.0
32,Papua Barat,NaN,NaN,NaN,NaN,NaN,760422.0,893400.0,915400.0,937500.0,959600.0
33,Papua,923440.0,1173875.0,1648708.0,1942627.0,2220934.0,2833381.0,3207400.0,3265200.0,3322500.0,3379300.0
34,Indonesia,119208229.0,147490298.0,179378946.0,194754808.0,206264595.0,237641326.0,258705000.0,261890900.0,265015300.0,268074600.0